---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci

inputs:
  - name: launched-instances
  - name: buildpacks-ci

run:
  path: buildpacks-ci/tasks/terminate-ami/run.rb