---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: gem
run:
  path: bash
  args:
    - -cl
    - buildpacks-ci/tasks/create-rubygems-release/run.rb
params:
  GEM_NAME:
  RUBYGEM_MIRROR:
  RUBYGEMS_ORG_API_KEY:
