name: bosh-lite-edge-compilation

director_uuid: REPLACE_WITH_DIRECTOR_UUID

releases:
- name: cf
  version: latest
- name: diego
  version: latest
- name: garden-runc
  version: latest
- name: cflinuxfs2-rootfs
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

jobs: []

update:
  canaries: 8
  max_in_flight: 8
  canary_watch_time: 1000-90000
  update_watch_time: 1000-90000
